# External modules to installed by r10k in modules/ dir
# Here mostly at latest version for sample purposes.
# In working environments specific versions should be defined.

# Sample recommended modules from Puppet forge
# mod "example42/tp", :latest
# mod "example42/tinydata", :latest

# mod "puppetlabs/concat", :latest
# mod "puppetlabs/stdlib", :latest
# mod "trlinkin/noop", :latest

# Sample module from git source
# mod'example42/tp',
#  :git => 'https://github.com/example42/puppet-tp',
#  :branch => 'master'
