# This class manages the installation and initialisation of apache
#
# @param ensure If to install or remove apache
# @param template The path to the erb template (as used in template()) to use
#                 to populate the Runner configuration file. Note that if you
#                 use the runners parameter this file is automatically generated
#                 during runners registration
# @param options An open hash of options you may use in your template
#
class profile::apache::tp (
  String                $ensure      = 'present',
  Optional[String]      $template    = undef,
  Optional[String]      $content     = undef,
  Optional[String]      $epp         = undef,
  Hash                  $options     = { },
  Optional[String] $default_site_source = undef,
) {

  $options_default = {
  }
  $real_options = $options_default + $options
  ::tp::install { 'apache' :
    ensure             => $ensure,
    auto_prerequisites => $auto_prerequisites,
  }

  if $template {
    ::tp::conf { 'apache':
      ensure       => $ensure,
      template     => $template,
      content      => $content,
      epp          => $epp,
      base_dir     => 'conf',
      options_hash => $real_options,
    }
  }

  if $default_site_source and $default_site_source != '' {
    $apache_settings = tp_lookup('apache','settings',hiera('tp::data_module', 'tinydata'),'merge')
    file { $apache_settings['data_dir_path']:
      ensure  => directory,
      source  => $default_site_source,
      recurse => true,
      purge   => true,
    }
  }
}
