---
# Default settings for all vms (they can be overridden on each node)
vm:
  memory: 1024                # MB or RAM to assign
  cpu: 1                      # Number of vCPU to assign to the VM
  box: ubuntu1604             # Box used for the VM, from the box list in vagrant/boxes.yaml
  puppet_apply: false         # Run puppet apply on the local control-repo during provisioning
  puppet_agent: true          # Run puppet agent during provisioning
  facter_external_facts: true # Create external facts in facts.d/$fact.txt. Note 1
  facter_trusted_facts: false # Create csr_attributes.yaml. Note 1

# Note 1:   Some facts are used in default hiera.yaml and needed for
# nodes classification. So it's better to set them, once.
# If you enable both external and trusted facts and keep the
# default manifests/site.pp you'll have a variable declaration error

# A local network is created among the VM. Here is configured.
network:
  range: 10.42.49.0/24  # Network address and mask to use
  ip_start_offset: 101  # Starting ip in the network for automatic assignement
  domain: foss.psick.io # Name of DNS domain for the created machines

# Puppet related settings
puppet:
  version: '5'                     # Version to use for OSS
  install_oss: true                   # If to install Puppet OSS agent on the VMS
  install_pe: false                   # If to install Puppet Enterprise agent on the VMS
  env: devel                          # Setting for the env fact (may be used in hiera.yaml)
  zone: foss                          # Setting for the zone fact (may be used in hiera.yaml)
  datacenter: vagrant                 # Setting for the datacenter fact (may be used in hiera.yaml)
  application: default                # Setting for the application fact (may be used in hiera.yaml)
  master_vm: puppet.foss.psick.io     # Name of the VM which play as Puppet server for the others
  master_fqdn: 'puppet.foss.psick.io' # FQDN of the Puppet server to use with puppet agent
  master_ip: '10.42.49.101'           # IP of the Puppet server. If set, relevant line with master_fqdn is         provisioned in /etc/hosts
  link_controlrepo: true              # Link the Puppet environment below # Set to false if r10k_install is true
  environment: host                   # Puppet environment to link to local control-repo and to use when Vagrant provisioning
  r10k_install: false                 # If to run r10k on Puppet server to deploy controlrepo
  controlrepo: /vagrant_puppet        # URL of the controlrepo to deploy via r10k on Puppet Server

# Vagrant settings
vagrant:
  hostmanager.manage_host: false # If true and you have the hostmanager plugin

# List of nodes shown in vagrant status
# Node names are based on the defined role. Here can be overridden vm defaults,
# it can be enforced a defined host name, added alieses, port forwarding and foss_role
nodes:
  - role: puppet
    application: puppetinfra
    foss_role: master
    puppet_apply: true
    memory: 6192
    cpu: 2
    box: centos7
    aliases:
      - puppet
    forwarded_port:
      guest: 443
      host: 19480
  - role: git
    application: puppetinfra
    puppet_apply: true
    puppet_agent: 0
    memory: 2048
    cpu: 2
    aliases:
      - git
    forwarded_port:
      guest:     443
      host: 19485
  - role: icinga
    count: 1
    forwarded_port:
      guest: 80
      host: 19484
  - role: foreman
    count: 1
    memory: 4096
    cpu: 2
    forwarded_port:
      guest: 3000
      host: 19482
  - role: grafana
    count: 1
    forwarded_port:
      guest: 3000
      host: 19483
  - role: influxdb
    count: 1
  - role: build
    count: 1
  - role: docker
    count: 1
  - role: jenkins
    cpu: 3
    count: 1
    memory: 6192
    box: ubuntu1604
    forwarded_port:
      guest: 8080
      host: 19481
  - role: ostest
    hostname_base: centos6
    count: 1
    box: centos6
  - role: ostest
    hostname_base: centos7
    count: 1
    box: centos7
