name    'lab42-snmpd'
version '1.0.0'

# dependency 'lab42/common', '>= 0.0.1'
# dependency 'lab42/monitor', '>= 0.0.1'
# dependency 'lab42/backup', '>= 0.0.1'
# dependency 'lab42/firewall', '>= 0.0.1'
