name    'lab42-foo'
version '0.1.0'

# dependency 'lab42/common', '>= 0.0.1'
# dependency 'lab42/monitor', '>= 0.0.1'
# dependency 'lab42/backup', '>= 0.0.1'
# dependency 'lab42/firewall', '>= 0.0.1'
