---
### Classification
psick::pre::linux_classes:
  puppet: psick::puppet::pe_agent
  hosts: psick::hosts::file
psick::base::linux_classes:
  icinga: psick::icinga2
  monitor_plugins: psick::monitor::nagiosplugins
#  sensu: psick::sensu
  ansible: psick::ansible
  bolt: psick::bolt
  dns: '' # In lab we leave DNS unmanaged
  puppet_postrun: psick::puppet::postrun
  packages: psick::packages

### Noop management
# Noop configuration on PE clients
psick::puppet::pe_agent::manage_noop: true
# Set here value for noop in agents' puppet.conf
psick::puppet::pe_agent::noop_mode: false

# Classes where we want to enforce resource application ALWAYS
# no_noop param enforces no-noop mode on the specific class even if
# noop mode is set client side or in Hiera's noop_mode setting.
# psick::dns::resolver::no_noop: true
# psick::hostname::no_noop: true
# psick::hosts::file::no_noop: true
# psick::puppet::gems::no_noop: true

# If psick::puppet::pe_agent::noop_mode: true
# this is needed to be able to revert it
psick::puppet::pe_agent::no_noop: true

### Puppet
psick::puppet::pe_agent::manage_environment: true
# Postrun command management
psick::puppet::postrun::ensure: absent
psick::puppet::postrun::template: 'psick/puppet/postrun_command_rerun.erb'
psick::puppet::postrun::path: '/usr/local/sbin/puppet_postrun'
psick::puppet::postrun::command: '/usr/local/sbin/puppet_postrun'
psick::puppet::gems::install_system_gems: false
psick::puppet::gems::install_gems:
  - msgpack

# Disabled updating host entry by psick::hostname
psick::hostname::update_host_entry: false
# Hosts file managed via file resource
psick::hosts::file::extra_hosts:
  - '10.42.43.101 puppet puppet.lab.psick.io'
  - '10.42.43.102 git git.lab.psick.io'
  - '10.42.43.103 cirunner cirunner.lab.psick.io'
  - '10.42.43.104 manageiq manageiq.lab.psick.io'
  - '10.42.43.105 rundeck rundeck.lab.psick.io'
  - '10.42.43.106 build build.lab.psick.io'
  - '10.42.43.107 docker docker.lab.psick.io'
  - '10.42.43.116 lamp lamp.lab.psick.io'
  - '10.42.43.111 sensu sensu.lab.psick.io'
  - '10.42.43.119 jenkins jenkins.lab.psick.io'

# Enable automatic updates on lab nodes and set schedule:
psick::update::cron_schedule: '42 4 * * *'

# Monitoring defaults:
psick::monitor:
  interface: 'eth1'

psick::icinga2::master: 'icinga.lab.psick.io'
psick::icinga2::is_client: true
psick::icinga2::install_cli: true

psick::sensu::is_client: true
psick::sensu::rabbitmq_host: 'sensu.lab.psick.io'
psick::sensu::rabbitmq_password: 'hiera_encrypt_in_the_real_world'
psick::sensu::rabbitmq_vhost: '/sensu'
psick::sensu::api_user: 'admin'
psick::sensu::api_password: 'sensu' # In real world encrypt with hiera eyaml

#sensu::client_http_socket:
#  bind: "%{facts.networking.ip}"
#  port: 3031
#  user: sensu
#  password: sensu
#sensu::client_servicenow:
#  configuration_item:
#    name: "%{::role} server"
#    os_version: "%{facts.os.release.full}"
#sensu::client_puppet:
#  nodename: "%{facts.networking.fqdn}"
#sensu::client_chef:
#  nodename: "%{facts.networking.fqdn}"
#sensu::client_ec2:
#  instance-id: "%{facts.networking.fqdn}"
sensu::client_register: true
sensu::client_deregister: false
#sensu::client_registration:
#  handler: 'servicenow'


psick::sensu::checks_params_hash:
  handlers:
    - 'graphite'
    - 'mailer'
  standalone: false
  subscribers: 'base'
psick::sensu::checks_hash:
  'check_cpu':
    command: '/opt/sensu/embedded/bin/check-cpu.rb'
  'check_cron':
    command: '/opt/sensu/embedded/bin/check-process.rb -p cron -C 1'
  'check_disk':
    command: '/opt/sensu/embedded/bin/check-disk-usage.rb -w 90 -c 95'
    interval: 3600
  'check_dns':
    command: "/opt/sensu/embedded/bin/check-dns.rb -d %{facts.networking.domain} -s 8.8.8.8 "
  'check_journal':
    command: '/opt/sensu/embedded/bin/check-journal.rb -q fail --since=-60minutes -c 1'
    interval: 3600
  'check_mem':
    command: '/opt/sensu/embedded/bin/check-memory-percent.rb -p -c 95 -w 90'
  'check_last_puppet_run':
    command: "/opt/sensu/embedded/bin/check-mtime.rb -f /opt/puppetlabs/puppet/cache/client_data/catalog/%{clientcert}.json -w 750 -c 1800"
    ensure: 'absent'

sensu::handlers:
  'graphite-occurrences':
    type: 'pipe'
    command: '/etc/sensu/handlers/graphite-occurrences.rb'
  'graphite':
    type: 'tcp'
    socket:
      host: "graphite.%{facts.networking.domain}"
      port: 2003
    mutator: 'only_check_output'
  'mailer':
    type: 'pipe'
    command: '/etc/sensu/handlers/mailer.rb'
    config:
      mail_from: "info@%{facts.networking.domain}"
      mail_to: "info@%{facts.networking.domain}"
      smtp_address: 'localhost'
      smtp_port: 25
      smtp_domain: "%{facts.networking.domain}"

psick::sensu::plugins_params_hash:
  pkg_provider: 'sensu_gem'
  type: 'package'

psick::sensu::plugins_hash:
  'sensu-plugins-conntrack': {}
  'sensu-plugins-cpu-checks': {}
  'sensu-plugins-cpu-usage': {}
  'sensu-plugins-dhcp': {}
  'sensu-plugins-disk-checks': {}
  'sensu-plugins-dns': {}
  'sensu-plugins-dnslookup': {}
  'sensu-plugins-disk-checks': {}
  'sensu-plugins-filesystem-checks': {}
  'sensu-plugins-filesize': {}
  'sensu-plugins-fsmounts': {}
#  'sensu-plugins-graphite': {}
  'sensu-plugins-hardware': {}
  'sensu-plugins-io-checks': {}
  'sensu-plugins-load-checks': {}
  'sensu-plugins-loadavg': {}
  'sensu-plugins-logs': {}
  'sensu-plugins-memory-checks': {}
  'sensu-plugins-network-checks': {}
  'sensu-plugins-ntp': {}
  'sensu-plugins-process-checks': {}

sensu::purge:
  'plugins': true
  'config': true
  'handlers': true
  'extensions': true
  'mutators': true

#Timezone
psick::timezone: 'Europe/Berlin'
psick::timezone::timezone_windows: 'Central European Standard Time'

# Puppet agents (on PE) sticky environment
psick::puppet::pe_agent::manage_environment: true

# Users
# psick::users::root_pw: hash_as_in_etc_shadow
psick::users::delete_unmanaged: false
psick::users::module: 'user'
psick::users::users_hash:
  al:
    ensure: present
    comment: 'Al'
    groups:
      - users
#    ssh_authorized_keys:
#      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC93uOkdIrvcA1ij6wxtL0wDKch7E2gFqID2xR1LnEVQRSP9OFmNQV+4B7fM/fAVpFs939qBDeDRabft1ZAP2hUIeKWxweNQ6wxxV3YhJbxt+g6RAqm37BI+/ynZnZ4vrQp3XHfxNFYGFqiaowiiQ3/0QLh8PHliDJroOUU7h2YNwKBWiqdgufLCrPgnalSZ3kfKa2Yd5sM+iyAYJ102sXcGIFjAXCmQU1y7aJXjrzXzPuugnHvVFPzAUjsvu0FAiE+m8EhfBiyy1+SjnMB838G3EwrqNW+sEZ6lXh637xensB2WJuH0lPooCgaeG6WCmYjVK9rblcOb3B0Pp8Vbhp5 al@lab.psick.io'

# OpenSSH
psick::openssh::tp::resources_hash:
  tp::conf:
    openssh:
      template: 'psick/generic/spaced.erb'
      options_hash:
        Protocol: 2
        PermitRootLogin: 'no'
        Subsystem: 'sftp /usr/libexec/openssh/sftp-server'

# Ansible
psick::ansible::master: puppet.lab.psick.io
psick::ansible::keyshare_method: storeconfigs

# Bolt
psick::bolt::master: puppet.lab.psick.io
psick::bolt::keyshare_method: storeconfigs
psick::bolt::ssh_user: bolt

# Enable package data collection on Puppet Enterprise
puppet_enterprise::profile::agent::package_inventory_enabled: true

