# Derived from puppetlabs-ntp

require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'

PuppetLint.configuration.fail_on_warnings = false
PuppetLint.configuration.send('relative')

