---
profiles:
  - '::docker'
  - '::docker::profile::builder'
##  - '::docker::profile::run_examples'
#  - '::docker::profile::build_examples'
  - '::profile::python::fabric'

profile::sysctl::settings:
  net.ipv4.conf.all.forwarding: 1

docker::username: example42
#docker::install_class: '' # To allow operations from Mac. Docker has to be installed.
docker::profile::run_examples::ensure: absent
docker::profile::builder::maintainer: 'Example42 GmbH <info@example42.com>'
docker::profile::builder::images:
  puppet-agent:
    ensure: present

