#!/bin/sh
# Managed by Puppet
# Script for automatic cobbler repo updates
# Sends an email when a single repo update fails

# Who gets failure alerts
email="root"

repolist=`cobbler list | grep "^repo" | cut -d " "  -f 2 `


for repo in $repolist ; do
	cobbler reposync --only $repo
	if [ $? != 0 ] ; then
		mail -s "Cobbler reposync failure: $repo on `hostname` " $email
		echo "$(date) Cobbler reposync on $repo FAILED" >> /var/log/cobbler_reposync.log
	fi
done
