# This class manages the installation and initialisation of apache
#
# @param ensure If to install or remove apache
# @param template The path to the erb template (as used in template()) to use
#                 to populate the Runner configuration file. Note that if you
#                 use the runners parameter this file is automatically generated
#                 during runners registration
# @param options An open hash of options you may use in your template
#
class profile::apache (
  String                $ensure      = 'present',
  Optional[String] $install_class = 'profile::apache::tp',
) {

  if $install_class { contain $install_class }

}
