#!/usr/bin/env ruby

require 'mcollective'
include MCollective::RPC

options = rpcoptions do |parser, options|
    parser.define_head "Management of APT Tasks"
    parser.banner = "Usage: mc-apt [filters] command"
    parser.separator ""
    parser.separator "Command can be one of the following:"
    parser.separator " upgrades - list number of available package upgrades"
    parser.separator " installed - list number of installed packages"
    parser.separator " clean - clean package archive files (i.e. apt-get clean)"
    parser.separator " update - update repository information (i.e. apt-get update)"
end

if ARGV.length == 1
    command = ARGV.shift
else
    puts("Please specify a command.")
    exit 1
end

if MCollective::Util.empty_filter?(options[:filter])
    print("Do you really want to operate on services unfiltered? (y/n): ")
    STDOUT.flush

    exit unless STDIN.gets.chomp =~ /^y$/
end

mc = rpcclient("apt", :options => options)

mc.progress = false

mc.send(command) do |resp|
    begin
        printf("%-40s: %s\n", resp[:senderid], resp[:body][:data])
    rescue RPCError => e
        puts "The RPC agent returned an error: #{e}"
    end
end
