name    'lab42-openssh'
version '0.1.1'

## Add dependencies, if any:
# dependency 'lab42/common', '>= 0.0.1'
# dependency 'lab42/monitor', '>= 0.0.1'
# dependency 'lab42/backup', '>= 0.0.1'
# dependency 'lab42/firewall', '>= 0.0.1'
